version: '3'

networks:
  shared:
    external: false

volumes:
  pg-data:

services:
#  traefik:
#    image: traefik:v2.3
#    command: --api.insecure=true --providers.docker
#    networks:
#      - shared
#    volumes:
##      - "./infra/traefik/traefik.yaml:/etc/traefik/traefik.yaml"
##      - "./infra/traefik/dynamic.yaml:/etc/traefik/dynamic/dynamic.yaml"
#      - "/var/run/docker.sock:/var/run/docker.sock"


  postgres:
    image: postgres:10.5
    restart: always
    container_name: postgres
    networks:
      - shared
    volumes:
      - "./infra/postgres/data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    env_file:
      - ./infra/postgres/.env

  auth:
    image: docker.pkg.github.com/alewkinr/io/auth:latest
    build:
      context: ./back/auth
      dockerfile: Dockerfile
    container_name: auth
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./back/auth/.env
    networks:
      - shared
    ports:
      - 8080:8080
    volumes:
    - ./back/auth:/service
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.auth.rule=Host(`*`)"
#      - "traefik.http.services.auth.loadbalancer.server.port=8080"
#      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)"
#      - "traefik.http.routers.auth.middlewares=cors@file,stripprefix@file"
#      - "traefik.http.routers.auth.entrypoints=web"