version: '3.2'

networks:
  shared:
    driver: bridge

volumes:
    prometheus_data: {}
    postgres_data: {}

services:
  traefik:
    image: traefik:v2.2.10
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./infra/traefik/traefik.yaml:/etc/traefik/traefik.yaml"
      - "./infra/traefik/dynamic.yaml:/etc/traefik/dynamic/dynamic.yaml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - shared

  postgres:
    image: postgres:10.5
    restart: always
    container_name: postgres
    volumes:
      - "./infra/postgres/data:/var/lib/postgresql/data"
      - "./infra/postgres/.env:/.env"
    ports:
      - 5432:5432
    env_file:
      - /.env

  auth:
    image: docker.pkg.github.com/alewkinr/io/auth:latest
    container_name: io
    restart: always
    expose:
      - 8080
    env_file:
      - /.env
    networks:
      - shared
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`*`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.middlewares=cors@file,stripprefix@file"
      - "traefik.http.routers.auth.entrypoints=web"