"""empty message

Revision ID: 3f56637eb167
Revises: e7ae9a34a569
Create Date: 2020-11-28 22:02:57.478944

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "3f56637eb167"
down_revision = "e7ae9a34a569"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("artist", sa.String(), nullable=True))
    op.add_column(
        "file",
        sa.Column("song_link", sqlalchemy_utils.types.url.URLType(), nullable=True),
    )
    op.add_column("file", sa.Column("title", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "title")
    op.drop_column("file", "song_link")
    op.drop_column("file", "artist")
    # ### end Alembic commands ###
