"""empty message

Revision ID: e7ae9a34a569
Revises: 9643bdf3bf0b
Create Date: 2020-11-28 12:22:49.893232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7ae9a34a569'
down_revision = '9643bdf3bf0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('saved_file_path', sa.String(), nullable=False))
    op.drop_column('file', 'file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('file', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('file', 'saved_file_path')
    # ### end Alembic commands ###
